// Gallery photos for らぁ麺 三湯 SANTAN — sourced from the shop's Tabelog visitor
// photos and Google Maps listing. Captions are short 4-language tags.
window.GALLERY_DATA = [
  { src: "pictures/gallery-1.jpg", alt: "Open kitchen at Santan",
    cap: { en: "Open Kitchen", jp: "オープンキッチン", ko: "오픈 키친", zh: "开放式厨房" } },
  { src: "pictures/gallery-2.jpg", alt: "Signature chicken paitan bowl",
    cap: { en: "Signature Bowl", jp: "看板の一杯", ko: "대표 메뉴", zh: "招牌拉面" } },
  { src: "pictures/gallery-3.jpg", alt: "Chicken paitan with egg and chashu",
    cap: { en: "Chicken Paitan", jp: "鶏白湯", ko: "닭 백탕", zh: "鸡白汤" } },
  { src: "pictures/gallery-4.jpg", alt: "Santan interior seating",
    cap: { en: "Counter Seats", jp: "カウンター席", ko: "카운터 석", zh: "吧台座位" } },
  { src: "pictures/gallery-5.jpg", alt: "Soft-boiled seasoned egg halves",
    cap: { en: "Soft-Boiled Egg", jp: "味玉", ko: "반숙 계란", zh: "溏心蛋" } },
  { src: "pictures/gallery-6.jpg", alt: "Torched chicken mazesoba",
    cap: { en: "Chicken Mazesoba", jp: "鶏まぜそば", ko: "닭 마제소바", zh: "鸡肉拌面" } },
  { src: "pictures/gallery-7.jpg", alt: "Chicken chashu close-up",
    cap: { en: "Chicken Chashu", jp: "鶏チャーシュー", ko: "닭 차슈", zh: "鸡叉烧" } },
  { src: "pictures/gallery-8.jpg", alt: "Counter with menu boards",
    cap: { en: "The Counter", jp: "カウンター", ko: "카운터", zh: "吧台" } },
  { src: "pictures/gallery-9.jpg", alt: "Chicken paitan bowl with herb garnish",
    cap: { en: "Chicken Paitan", jp: "鶏白湯", ko: "닭 백탕", zh: "鸡白汤" } },
  { src: "pictures/gallery-10.jpg", alt: "Foam paitan bowl",
    cap: { en: "Foam Paitan", jp: "泡白湯", ko: "거품 백탕", zh: "泡沫白汤" } },
  { src: "pictures/gallery-11.jpg", alt: "Espuma foam close-up with spoon",
    cap: { en: "Espuma Foam", jp: "エスプーマ", ko: "에스푸마 거품", zh: "意式泡沫" } },
  { src: "pictures/gallery-12.jpg", alt: "Lifting thin straight noodles",
    cap: { en: "Straight Noodles", jp: "ストレート麺", ko: "스트레이트 면", zh: "直面" } },
  { src: "pictures/gallery-13.jpg", alt: "Yukihime bowl overhead",
    cap: { en: "Yukihime Bowl", jp: "雪姫", ko: "유키히메", zh: "雪姬" } },
  { src: "pictures/gallery-14.jpg", alt: "Seasonal bowl with vegetables and egg",
    cap: { en: "Seasonal Bowl", jp: "季節の一杯", ko: "계절 한 그릇", zh: "季节限定" } },
  { src: "pictures/gallery-15.jpg", alt: "Inside Santan, counter view",
    cap: { en: "Inside Santan", jp: "店内の様子", ko: "三湯 매장", zh: "走进三湯" } },
  { src: "pictures/gallery-16.jpg", alt: "Santan storefront exterior",
    cap: { en: "Our Storefront", jp: "店舗外観", ko: "매장 외관", zh: "店铺外观" } },
];
