// Menu data for らぁ麺 三湯 SANTAN. Each item carries name + description in four
// languages (en / jp / ko / zh); the site shows the active language only.
// Prices are best-effort placeholders in the shop's sub-¥1,000 range — confirm
// with the shop before publishing. The espuma "foam" (泡) paitan and the premium
// "雪姫 (Yukihime)" bowl reflect what Tabelog reviewers describe.
window.MENU_DATA = [
  // ---- Signature -------------------------------------------------------
  {
    active: true, featured: true, category: "Signature",
    nameEn: "Chicken Paitan Ramen", nameJp: "鶏白湯らぁ麺",
    nameKo: "닭 백탕 라멘", nameZh: "鸡白汤拉面",
    price: 900, badge: { en: "Signature", jp: "看板", ko: "대표", zh: "招牌" },
    descEn: "Our house bowl — chicken bones simmered for hours into a silky white paitan, crowned with a fine espuma foam over thin straight noodles.",
    descJp: "鶏ガラを長時間炊き上げた、とろりと白い白湯。きめ細かなエスプーマの泡をまとわせ、細ストレート麺と合わせた看板の一杯。",
    descKo: "닭 뼈를 오래도록 고아낸 뽀얀 백탕에 고운 에스푸마 거품을 얹고, 가는 스트레이트 면을 더한 대표 메뉴.",
    descZh: "招牌之作——鸡骨慢熬数小时成醇白汤头，覆以细腻意式泡沫，配纤细直面。",
    image: "pictures/menu/chicken-paitan.jpg",
  },
  {
    active: true, featured: true, category: "Signature",
    nameEn: "Yukihime — Snow Foam Paitan", nameJp: "雪姫（ゆきひめ）",
    nameKo: "유키히메 (雪姫)", nameZh: "雪姬",
    price: 1150, badge: { en: "Premium", jp: "特上", ko: "프리미엄", zh: "特级" },
    descEn: "Our premium bowl — an extra-rich foam paitan, refined almost like French cuisine, finished with chashu, seasoned egg and rare toppings.",
    descJp: "特上の一杯。より濃厚な泡白湯を、フレンチのように上品に仕立て、チャーシュー・味玉・特製具材で華やかに。",
    descKo: "최상급 한 그릇. 한층 진한 거품 백탕을 프렌치처럼 우아하게 완성하고 차슈·아지타마·특제 고명을 얹었습니다.",
    descZh: "顶级之选——更为浓郁的泡沫白汤，宛如法式料理般精致，佐以叉烧、溏心蛋与特制配料。",
    image: "pictures/menu/special-paitan.jpg",
  },
  // ---- Ramen -----------------------------------------------------------
  {
    active: true, featured: true, category: "Ramen",
    nameEn: "Shoyu Ramen", nameJp: "醤油らぁ麺",
    nameKo: "쇼유 라멘 (간장)", nameZh: "酱油拉面",
    price: 850, badge: null,
    descEn: "A clear chicken stock rounded with aged soy tare — fragrant, clean and quietly complex.",
    descJp: "澄んだ鶏出汁に熟成醤油ダレを合わせた、香り高く端正な一杯。",
    descKo: "맑은 닭 육수에 숙성 간장 타레를 더한, 향이 깊고 정갈한 한 그릇.",
    descZh: "清澈鸡汤佐以熟成酱油调味，香气清雅、层次内敛。",
    image: "pictures/menu/shoyu.jpg",
  },
  {
    active: true, featured: true, category: "Ramen",
    nameEn: "Shio Ramen", nameJp: "塩らぁ麺",
    nameKo: "시오 라멘 (소금)", nameZh: "盐味拉面",
    price: 850, badge: null,
    descEn: "Delicate salt tare lets the chicken broth speak for itself — the purest read of the soup.",
    descJp: "繊細な塩ダレで鶏の旨味をそのまま引き出した、スープ本来を味わう一杯。",
    descKo: "섬세한 소금 타레로 닭 육수 본연의 맛을 살린, 가장 순수한 한 그릇.",
    descZh: "以细致盐味调料凸显鸡汤本味，最纯粹的一碗。",
    image: "pictures/menu/shio.jpg",
  },
  {
    active: true, featured: true, category: "Ramen",
    nameEn: "Ajitama Ramen", nameJp: "味玉らぁ麺",
    nameKo: "아지타마 라멘 (반숙란)", nameZh: "溏心蛋拉面",
    price: 950, badge: null,
    descEn: "Shoyu or shio ramen crowned with a slow-marinated soft-centred egg.",
    descJp: "醤油または塩のらぁ麺に、じっくり漬け込んだとろとろ味玉をのせて。",
    descKo: "쇼유 또는 시오 라멘에 정성껏 절인 반숙 아지타마를 올렸습니다.",
    descZh: "酱油或盐味拉面，加上慢渍溏心蛋。",
    image: "pictures/menu/ajitama.jpg",
  },
  // ---- Tsukemen & Mazesoba --------------------------------------------
  {
    active: true, featured: true, category: "Tsukemen & Mazesoba",
    nameEn: "Chicken Paitan Tsukemen", nameJp: "鶏白湯つけ麺",
    nameKo: "닭 백탕 츠케멘", nameZh: "鸡白汤蘸面",
    price: 950, badge: null,
    descEn: "Chilled noodles served beside a thick, concentrated paitan dipping broth.",
    descJp: "しめた麺を、濃度を高めた濃厚鶏白湯のつけ汁で味わう一皿。",
    descKo: "차갑게 조인 면을 진하게 농축한 닭 백탕 츠케지루에 찍어 즐기는 한 그릇.",
    descZh: "冰镇面条搭配浓缩醇厚的白汤蘸汁。",
    image: "pictures/menu/tsukemen.jpg",
  },
  {
    active: true, featured: true, category: "Tsukemen & Mazesoba",
    nameEn: "Chicken Mazesoba", nameJp: "鶏まぜそば",
    nameKo: "닭 마제소바", nameZh: "鸡肉拌面",
    price: 900, badge: { en: "New", jp: "新", ko: "신메뉴", zh: "新品" },
    descEn: "Brothless noodles tossed with chicken tare, minced chicken, egg yolk and scallion — mix well before eating.",
    descJp: "スープなしの和え麺。鶏ダレ・鶏そぼろ・卵黄・ねぎをよく混ぜてどうぞ。",
    descKo: "국물 없는 비빔면. 닭 타레·닭 소보로·노른자·파를 잘 섞어 드세요.",
    descZh: "无汤拌面，佐鸡肉调味汁、鸡肉燥、蛋黄与葱花，拌匀后享用。",
    image: "pictures/menu/mazesoba.jpg",
  },
  // ---- Toppings --------------------------------------------------------
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Seasoned Egg", nameJp: "味玉",
    nameKo: "아지타마 (반숙란)", nameZh: "溏心蛋",
    price: 120, badge: null,
    descEn: "Soft-centred egg marinated in our house tare.",
    descJp: "自家製ダレに漬けた半熟の味付け玉子。",
    descKo: "자가제 타레에 절인 반숙 계란.",
    descZh: "自家调味汁腌渍的溏心蛋。",
    image: "pictures/menu/egg.jpg",
  },
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Extra Chashu", nameJp: "追いチャーシュー",
    nameKo: "차슈 추가", nameZh: "加点叉烧",
    price: 250, badge: null,
    descEn: "Additional slices of low-temperature chicken chashu.",
    descJp: "低温調理した鶏チャーシューの追加。",
    descKo: "저온 조리한 닭 차슈 추가.",
    descZh: "加点低温慢煮鸡叉烧。",
    image: "pictures/menu/chashu.jpg",
  },
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Menma", nameJp: "メンマ",
    nameKo: "멘마 (죽순)", nameZh: "笋干",
    price: 120, badge: null,
    descEn: "Seasoned bamboo shoots.", descJp: "味付けメンマ。",
    descKo: "양념 죽순(멘마).", descZh: "调味笋干。",
    image: "pictures/menu/menma.jpeg",
  },
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Extra Nori", nameJp: "海苔",
    nameKo: "김 추가", nameZh: "加点海苔",
    price: 100, badge: null,
    descEn: "Crisp sheets of seaweed.", descJp: "パリッと香る海苔。",
    descKo: "바삭한 김.", descZh: "香脆海苔。",
    image: "pictures/menu/nori.jpeg",
  },
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Extra Negi", nameJp: "ねぎ増し",
    nameKo: "파 추가", nameZh: "加点葱花",
    price: 100, badge: null,
    descEn: "A generous heap of fresh scallion.", descJp: "たっぷりの刻みねぎ。",
    descKo: "듬뿍 담은 송송 썬 파.", descZh: "满满一把新鲜葱花。",
    image: "pictures/menu/negi.jpg",
  },
  {
    active: true, featured: false, category: "Toppings",
    nameEn: "Kaedama (Extra Noodles)", nameJp: "替え玉",
    nameKo: "카에다마 (사리 추가)", nameZh: "加面（替玉）",
    price: 150, badge: null,
    descEn: "An extra portion of noodles for your remaining broth.",
    descJp: "残ったスープに、替え玉の追加麺を。",
    descKo: "남은 국물에 즐기는 사리 추가.",
    descZh: "为剩余汤头再加一份面。",
    image: "pictures/menu/kaedama.jpg",
  },
  // ---- Rice & Sides ----------------------------------------------------
  {
    active: true, featured: false, category: "Rice & Sides",
    nameEn: "Chashu Bowl", nameJp: "チャーシュー丼",
    nameKo: "차슈 덮밥", nameZh: "叉烧饭",
    price: 350, badge: null,
    descEn: "A small bowl of rice topped with chicken chashu and tare — pairs perfectly with any ramen.",
    descJp: "鶏チャーシューとタレをのせた小丼。どのらぁ麺とも好相性。",
    descKo: "닭 차슈와 타레를 올린 미니 덮밥. 어느 라멘과도 잘 어울립니다.",
    descZh: "小碗米饭铺上鸡叉烧与调味汁，与任何拉面都相配。",
    image: "pictures/menu/chashu-don.jpg",
  },
  {
    active: true, featured: false, category: "Rice & Sides",
    nameEn: "Chicken Soboro Bowl", nameJp: "鶏そぼろ丼",
    nameKo: "닭 소보로 덮밥", nameZh: "鸡肉燥饭",
    price: 350, badge: null,
    descEn: "Minced seasoned chicken over warm rice.",
    descJp: "温かいご飯に鶏そぼろをのせた一杯。",
    descKo: "따뜻한 밥 위에 닭 소보로를 올린 덮밥.",
    descZh: "温热米饭上铺鸡肉燥。",
    image: "pictures/menu/soboro-don.jpg",
  },
  {
    active: true, featured: false, category: "Rice & Sides",
    nameEn: "White Rice", nameJp: "白ご飯",
    nameKo: "흰쌀밥", nameZh: "白米饭",
    price: 150, badge: null,
    descEn: "A bowl of steamed rice — finish your soup over it.",
    descJp: "白ご飯。残ったスープの〆にも。",
    descKo: "흰쌀밥. 남은 국물의 마무리로도.",
    descZh: "白米饭，亦可用来收尾汤头。",
    image: "pictures/menu/rice.webp",
  },
  // ---- Drinks ----------------------------------------------------------
  {
    active: true, featured: false, category: "Drinks",
    nameEn: "Green Tea", nameJp: "緑茶",
    nameKo: "녹차", nameZh: "绿茶",
    price: 150, badge: null,
    descEn: "Chilled Japanese green tea.", descJp: "冷たい緑茶。",
    descKo: "시원한 녹차.", descZh: "冰镇日式绿茶。",
    image: "pictures/menu/tea.webp",
  },
  {
    active: true, featured: false, category: "Drinks",
    nameEn: "Bottled Beer", nameJp: "瓶ビール",
    nameKo: "병맥주", nameZh: "瓶装啤酒",
    price: 550, badge: null,
    descEn: "A cold bottle to go with your bowl.",
    descJp: "らぁ麺のお供に、冷えた瓶ビール。",
    descKo: "라멘과 곁들이는 시원한 병맥주.",
    descZh: "搭配拉面的冰镇瓶装啤酒。",
    image: "pictures/menu/beer.jpg",
  },
  {
    active: true, featured: false, category: "Drinks",
    nameEn: "Soft Drink", nameJp: "ソフトドリンク",
    nameKo: "소프트드링크", nameZh: "软饮",
    price: 200, badge: null,
    descEn: "Assorted soft drinks.", descJp: "各種ソフトドリンク。",
    descKo: "각종 소프트드링크.", descZh: "各式软饮。",
    image: "pictures/menu/soft-drink.webp",
  },
];
